# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo processor.py al contenedor
COPY processor.py /app/

# Instala las dependencias necesarias
RUN pip install paho-mqtt pandas scikit-learn

# Comando para ejecutar el script cuando el contenedor se inicie
CMD ["python", "processor.py"]
